baseurl = "https://cnu.name/"
DefaultContentLanguage = "en"
title = "Srinivasan Rangarajan"
theme = "beautifulhugo"
Paginate = 5
googleAnalytics = "UA-6819872-4"
pygmentsuseclasses = true
PygmentsCodeFences = true
pygmentstyle = "monokai"
MetaDataFormat = "yaml"
disqusShortname = "cnu"

[author]
    Handle = "cnu"
    FirstName = "Srinivasan"
    LastName = "Rangarajan"


[params]
    subtitle = "Software Engineering, Product Design, Marketing, and more."
    dateFormat = "January 2, 2006"
    commit = false
    rss = true
    comments = true

[Author]
    name = "Srinivasan Rangarajan"
    email = "srinivasanr@gmail.com"
    facebook = "cnus8n"
    github = "cnu"
    twitter = "cnu"
    reddit = "cnu"
    linkedin = "cnus8n"
    stackoverflow = "users/1448/cnu"

#[[menu.main]]
#    name = "Blog"
#    url = ""
#    weight = 1

#[[menu.main]]
#    name = "About"
#    url = "about"
#    weight = 3

#[[menu.main]]
#    name = "Projects"
#    url = "projects"
#    weight = 2
