baseurl = "http://cnu.name/"
languageCode = "en-us"
title = "Site"
theme = "internet-weblog"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = "UA-6819872-4"
pygmentstyle = "monokai"
MetaDataFormat = "yaml"

[author]
    Handle = "cnu"
    FirstName = "Srinivasan"
    LastName = "Rangarajan"
    AboutPage = "/about"
    Location = "Chennai, IN"
    FlickrID = "31114004@N00"

[params]
    Description = "$ cat /dev/random > cnu.name/new/"
    ShowCopyright = true
    RSSEnabled = true
    RSSSections = [ "Posts", "Microposts", "Photos" ]

[[menu.main]]
    name = "Posts"
    weight = 1
    identifier = "posts"
    url = "/posts/"

# [[menu.main]]
#     name = "Microposts"
#     weight = 2
#     identifier = "microposts"
#     url = "/microposts/"

# [[menu.main]]
#     name = "Photos"
#     weight = 3
#     identifier = "photos"
#     url = "/photos/"

# [[menu.main]]
#     name = "Projects"
#     weight = 4
#     identifier = "projects"
#     url = "/projects/"