backend:
  name: github
  repo: cnu/cnu.name # Path to your Github repository
  branch: master # Branch to update
media_folder: "static/img" # Media files will be stored in the repo under
public_folder: "/img" # The src attribute for uploaded media will begin with
